/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104333-g13141339c1-20211013"
#endif /* AVUTIL_FFVERSION_H */
